[CmdletBinding(SupportsShouldProcess = $true)]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$baseDir = Split-Path -Parent $PSScriptRoot
$downloadsDir = Join-Path $baseDir "downloads"
$backupDir = Join-Path $baseDir ("backup-" + (Get-Date -Format "yyyyMMdd-HHmmss") + "-biospreboot")
$packageUrl = "http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2020-02-29.7z"
$packagePath = Join-Path $downloadsDir "grub4dos-0.4.6a-2020-02-29.7z"
$extractRoot = Join-Path $downloadsDir "grub4dos"
$extractDir = Join-Path $extractRoot "grub4dos-0.4.6a"
$sevenZip = "C:\Program Files\7-Zip\7z.exe"
$bootSectorTarget = "C:\gt330mfix.mbr"
$grldrTarget = "C:\grldr"
$menuLstTarget = "C:\menu.lst"
$entryDescription = "Windows 11 (GT330M preboot fix)"
$bootManagerId = "{bootmgr}"

function Assert-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this script from an elevated PowerShell session."
    }
}

function Invoke-BcdEdit {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    $escapedArgs = foreach ($argument in $Arguments) {
        if ($argument -match '\s') {
            '"' + $argument.Replace('"', '\"') + '"'
        }
        else {
            $argument
        }
    }

    $output = & cmd.exe /c ("bcdedit " + ($escapedArgs -join " ")) 2>&1
    $text = ($output | Out-String).Trim()
    if ($LASTEXITCODE -ne 0) {
        throw "bcdedit $($Arguments -join ' ') failed: $text"
    }
    return $text
}

function Get-BcdBootManagerState {
    $raw = Invoke-BcdEdit -Arguments @("/enum", $bootManagerId)
    $state = [ordered]@{
        Default = $null
        Timeout = $null
        Raw = $raw
    }

    if ($raw -match "(?m)^\s*default\s+(\{[^\}]+\})$") {
        $state.Default = $matches[1]
    }

    if ($raw -match "(?m)^\s*timeout\s+(\d+)$") {
        $state.Timeout = [int]$matches[1]
    }

    return [pscustomobject]$state
}

function Get-ExistingEntryGuid {
    $raw = Invoke-BcdEdit -Arguments @("/enum", "all", "/v")
    $blocks = $raw -split "(\r?\n){2,}"
    foreach ($block in $blocks) {
        if ($block -match [regex]::Escape($entryDescription)) {
            if ($block -match "(?m)^\s*identifier\s+(\{[^\}]+\})$") {
                return $matches[1]
            }
        }
        if ($block -match [regex]::Escape("\gt330mfix.mbr")) {
            if ($block -match "(?m)^\s*identifier\s+(\{[^\}]+\})$") {
                return $matches[1]
            }
        }
    }

    return $null
}

function Backup-IfExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) {
        return $null
    }

    $targetPath = Join-Path $backupDir ([IO.Path]::GetFileName($SourcePath))
    Copy-Item -LiteralPath $SourcePath -Destination $targetPath -Force
    return $targetPath
}

function Ensure-Grub4DosPayload {
    if (-not (Test-Path -LiteralPath $sevenZip)) {
        throw "7-Zip was not found at $sevenZip"
    }

    New-Item -ItemType Directory -Path $downloadsDir -Force | Out-Null

    if (-not (Test-Path -LiteralPath $packagePath)) {
        Invoke-WebRequest -Uri $packageUrl -OutFile $packagePath
    }

    if (-not (Test-Path -LiteralPath (Join-Path $extractDir "grldr.mbr"))) {
        New-Item -ItemType Directory -Path $extractRoot -Force | Out-Null
        & $sevenZip x -y $packagePath ("-o" + $extractRoot) | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to extract $packagePath"
        }
    }
}

function New-MenuLstContent {
    @(
        "# Auto-generated by Install-GT330M-BiosPrebootFix.ps1"
        "default 0"
        "timeout 3"
        ""
        "title Windows 11 (GT330M preboot fix)"
        "  setpci -s ""00:01.0"" 3e.b=8"
        "  setpci -s ""01:00.0"" 04.b=7"
        "  setpci -s ""00:00.0"" 50.W=2"
        "  setpci -s ""00:00.0"" 54.B=3"
        "  find --set-root /bootmgr"
        "  chainloader /bootmgr"
        ""
        "title Windows 11 (standard boot)"
        "  find --set-root /bootmgr"
        "  chainloader /bootmgr"
    ) -join [Environment]::NewLine
}

Assert-Administrator
Ensure-Grub4DosPayload
New-Item -ItemType Directory -Path $backupDir -Force | Out-Null

$bootManagerState = Get-BcdBootManagerState
$existingGuid = Get-ExistingEntryGuid

$stateBefore = [ordered]@{
    Timestamp = (Get-Date).ToString("o")
    EntryDescription = $entryDescription
    PreviousDefault = $bootManagerState.Default
    PreviousTimeout = $bootManagerState.Timeout
    ExistingEntryGuid = $existingGuid
    BackedUpFiles = [ordered]@{
        BootSector = Backup-IfExists -SourcePath $bootSectorTarget
        Grldr = Backup-IfExists -SourcePath $grldrTarget
        MenuLst = Backup-IfExists -SourcePath $menuLstTarget
    }
}

Invoke-BcdEdit -Arguments @("/export", (Join-Path $backupDir "bcd-before.bcd")) | Out-Null
$stateBefore | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $backupDir "state-before.json")

if ($existingGuid) {
    if ($PSCmdlet.ShouldProcess($existingGuid, "delete previous GT330M preboot entry")) {
        Invoke-BcdEdit -Arguments @("/delete", $existingGuid, "/f") | Out-Null
    }
}

if ($PSCmdlet.ShouldProcess("C:\\", "copy grub4dos payload and create menu.lst")) {
    Copy-Item -LiteralPath (Join-Path $extractDir "grldr.mbr") -Destination $bootSectorTarget -Force
    Copy-Item -LiteralPath (Join-Path $extractDir "grldr") -Destination $grldrTarget -Force
    Set-Content -LiteralPath $menuLstTarget -Value (New-MenuLstContent) -NoNewline
}

$createOutput = Invoke-BcdEdit -Arguments @("/create", "/d", $entryDescription, "/application", "BOOTSECTOR")
if ($createOutput -notmatch "(\{[^\}]+\})") {
    throw "Could not parse the new BCD identifier from: $createOutput"
}
$newGuid = $matches[1]

if ($PSCmdlet.ShouldProcess($newGuid, "configure BIOS preboot chainload entry")) {
    Invoke-BcdEdit -Arguments @("/set", $newGuid, "device", "partition=C:") | Out-Null
    Invoke-BcdEdit -Arguments @("/set", $newGuid, "path", "\gt330mfix.mbr") | Out-Null
    Invoke-BcdEdit -Arguments @("/displayorder", $newGuid, "/addfirst") | Out-Null
    Invoke-BcdEdit -Arguments @("/timeout", "5") | Out-Null
    Invoke-BcdEdit -Arguments @("/default", $newGuid) | Out-Null
}

$stateAfter = [ordered]@{
    Timestamp = (Get-Date).ToString("o")
    EntryGuid = $newGuid
    BootManager = Get-BcdBootManagerState
    Entry = Invoke-BcdEdit -Arguments @("/enum", $newGuid)
}
$stateAfter | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $backupDir "state-after.json")

Write-Host "Installed GT330M BIOS preboot fix entry."
Write-Host "Backup saved to: $backupDir"
Write-Host "Boot entry GUID: $newGuid"
Write-Host "The fix entry is now the default boot option with a 5-second timeout."
